import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { RESOURCE_PAGES, getResourcePage } from '@/lib/resource-pages'
import { DOCUMENT_TYPES } from '@/lib/document-types'
import { SiteNav } from '@/components/SiteNav'
import { SiteFooter } from '@/components/SiteFooter'
import { SITE_NAME, SITE_URL } from '@/lib/site'

export function generateStaticParams() {
  return RESOURCE_PAGES.map((p) => ({ slug: p.slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const page = getResourcePage(slug)
  if (!page) return {}

  const title = `${page.tradeLabel} in ${page.stateLabel}: SOP, Quote & Business Document Templates`
  const description = `Business paperwork templates for ${page.tradeSearchTerm}s in ${page.stateLabel}: SOPs, quote templates, subcontractor packs, and business policies, generated for your trade. Two documents free, full set is a one-time $149.`

  return {
    title,
    description,
    alternates: { canonical: `/resources/${page.slug}` },
    openGraph: {
      title,
      description,
      url: `/resources/${page.slug}`,
      type: 'article',
    },
  }
}

export default async function ResourcePage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const page = getResourcePage(slug)
  if (!page) notFound()

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: `Business document templates for ${page.tradeLabel.toLowerCase()} in ${page.stateLabel}`,
    description: `SOPs, quote templates, subcontractor packs, and business policies for ${page.tradeSearchTerm}s in ${page.stateLabel}, generated by Docs Rok.`,
    author: { '@type': 'Organization', name: SITE_NAME, url: SITE_URL },
    publisher: { '@type': 'Organization', name: SITE_NAME, url: SITE_URL },
    mainEntityOfPage: `${SITE_URL}/resources/${page.slug}`,
  }

  return (
    <div className="min-h-screen bg-paper">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />

      <SiteNav />

      {/* Hero */}
      <section className="relative overflow-hidden border-b border-line">
        <div className="bp-grid pointer-events-none absolute inset-0" />
        <div className="relative mx-auto max-w-3xl px-4 py-16 sm:px-6">
          <div className="mb-6 inline-flex items-center gap-2 border-l-2 border-brand bg-white/60 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-ink-2">
            {page.tradeLabel} &middot; {page.stateLabel}
          </div>
          <h1 className="font-display text-4xl font-extrabold leading-tight tracking-tight text-ink sm:text-5xl">
            Business paperwork templates for {page.tradeSearchTerm}s in {page.stateLabel}
          </h1>
          <p className="mt-6 text-lg text-ink-2">{page.painPoint}</p>
          <p className="mt-4 text-lg text-ink-2">It shows up as soon as {page.scenario}</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row">
            <Link
              href="/signup"
              className="rounded-md bg-brand px-8 py-3.5 text-center text-base font-semibold text-white transition-colors hover:bg-brand-dark"
            >
              Start free
            </Link>
            <Link
              href="/#pricing"
              className="rounded-md border border-line bg-white px-8 py-3.5 text-center text-base font-semibold text-ink transition-colors hover:bg-paper-dim"
            >
              See pricing
            </Link>
          </div>
          <p className="mt-4 text-xs text-muted">
            Two documents free, no credit card. Full set is a one-time $149, no subscription.
          </p>
        </div>
      </section>

      {/* Local note */}
      <div className="border-b border-line bg-paper-dim/70 px-4 py-6 sm:px-6">
        <div className="mx-auto max-w-3xl text-sm text-ink-2">
          <p>
            Businesses in {page.stateLabel} register their trade licence with {page.regulator}.
            Docs Rok doesn&apos;t touch licensing or compliance paperwork, it generates the
            day-to-day business documents most {page.tradeSearchTerm}s never get around to
            writing. {page.marketNote}
          </p>
        </div>
      </div>

      {/* What's included */}
      <section className="px-4 py-16 sm:px-6">
        <div className="mx-auto max-w-4xl">
          <h2 className="mb-10 text-center font-display text-2xl font-bold tracking-tight text-ink sm:text-3xl">
            What you get, customised to your trade and state
          </h2>
          <div className="grid gap-px overflow-hidden rounded-lg border border-line bg-line sm:grid-cols-2">
            {DOCUMENT_TYPES.map((doc) => (
              <div key={doc.name} className="bg-paper p-6">
                <span className="mb-3 flex h-10 w-10 items-center justify-center rounded-md bg-brand-light text-brand">
                  <doc.icon className="h-5 w-5" strokeWidth={1.75} />
                </span>
                <h3 className="font-display text-lg font-bold text-ink">{doc.name}</h3>
                <p className="mt-1 text-sm text-muted">{doc.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-ink px-4 py-16 text-center sm:px-6">
        <div className="mx-auto max-w-2xl">
          <h2 className="font-display text-2xl font-bold text-white sm:text-3xl">
            Get your {page.tradeSearchTerm} paperwork sorted today
          </h2>
          <p className="mb-8 mt-4 text-lg text-white/70">
            Start with two documents free, no credit card. Unlock the full set for a one-time
            $149 whenever you&apos;re ready.
          </p>
          <Link
            href="/signup"
            className="inline-block rounded-md bg-brand px-10 py-4 text-base font-bold text-white transition-colors hover:bg-brand-dark"
          >
            Start free
          </Link>
        </div>
      </section>

      <SiteFooter />
    </div>
  )
}
