import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Docs Rok',
  description: 'Terms of Service for Docs Rok — the business paperwork platform for Australian trade businesses.',
}

const LAST_UPDATED = '14 July 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-orange-600 font-bold text-lg tracking-tight">Docs Rok</Link>
          <Link href="/login" className="text-sm text-gray-500 hover:text-gray-800 transition-colors">Sign in</Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: {LAST_UPDATED}</p>

        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-10">
          <p className="text-sm text-amber-800 font-medium">
            Important: Documents generated by Docs Rok are business templates and starting points —
            standard operating procedures, quote templates, and policy documents. They are not legal,
            financial, or professional advice, and you should review and adapt each document to your
            business before use.
          </p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-gray-700">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Agreement to terms</h2>
            <p>
              By creating an account with Docs Rok (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you (&ldquo;you&rdquo;, &ldquo;the customer&rdquo;)
              agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not
              use the service.
            </p>
            <p className="mt-3">
              These Terms form a legally binding agreement between you and Docs Rok, governed by the
              laws of Queensland, Australia.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Description of service</h2>
            <p>
              Docs Rok is a software-as-a-service platform that generates internal business-operations
              document templates for Australian trade and service businesses, in any state. Documents
              are generated using artificial intelligence based on information you provide about your
              business.
            </p>
            <p className="mt-3">Documents generated by Docs Rok include:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Standard Operating Procedures (SOPs)</li>
              <li>Subcontractor and new-hire welcome packs</li>
              <li>Quote and proposal templates</li>
              <li>Business policy documents (customer service, complaints handling, terms of trade, cancellation/refund policy, code of conduct)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Important disclaimer — not legal, financial, or professional advice</h2>
            <div className="bg-gray-50 rounded-lg p-4 space-y-3">
              <p>
                <strong>Documents generated by Docs Rok are templates and starting points only.</strong> They
                are not legal, financial, or professional advice, and using them does not guarantee any
                particular business or commercial outcome.
              </p>
              <p>
                Every business operates differently. A generated SOP, quote template, or policy document
                reflects general good practice for your stated trade and business size — it is not a
                substitute for your own judgement about how your business actually runs.
              </p>
              <p>
                You must review each document before using it, and adapt it to reflect your actual
                processes, pricing, and terms. Placeholders in quote templates must be completed with
                real, accurate figures for each job.
              </p>
              <p>
                For terms of trade, contracts, or other documents with legal effect, you should have
                a lawyer review the final version before relying on it with customers. Docs Rok is not
                a substitute for professional legal or accounting advice.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Your account</h2>
            <p>
              You must provide accurate information when creating your account. You are responsible
              for maintaining the security of your password and for all activity under your account.
              Notify us immediately at{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>{' '}
              if you suspect unauthorised access.
            </p>
            <p className="mt-3">
              Each account may only be used by one business entity. You may not share your account
              credentials with other businesses or use the service to generate documents for businesses
              other than your own (except where you are an authorised representative of that business).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Free plan</h2>
            <p>
              New accounts include two documents free of charge: one Standard Operating Procedure
              and one quote/proposal template, both generated for your business. No credit card is
              required and there is no time limit. These documents remain available in your account
              whether or not you go on to purchase Full Access.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Full Access purchase</h2>
            <p>
              Full Access is a one-time purchase of $149 AUD (ex-GST) that unlocks generation of your
              complete document set: all core-process Standard Operating Procedures, a quote/proposal
              template for each service you offer, a subcontractor and new-hire welcome pack, and all
              business policy documents. GST (10%) is added where applicable under Australian tax law.
            </p>
            <p className="mt-3">
              This is not a subscription. There is no recurring charge, no billing cycle, and nothing
              to cancel. Payment is processed by Stripe, Inc. as a single transaction. Your access and
              your generated documents do not expire.
            </p>
            <p className="mt-3">
              We reserve the right to change the price of Full Access at any time. A change in price
              does not affect a purchase already completed.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Refunds</h2>
            <p>
              Full Access is delivered immediately on payment, and your documents are generated on
              demand at real cost to us. For that reason we do not offer change-of-mind refunds once
              your full document set has been generated. The free plan exists so you can see the
              actual quality and format of our documents, generated for your own business, before
              you decide to pay anything.
            </p>
            <p className="mt-3">
              Nothing in these terms excludes, restricts or modifies the consumer guarantees under the
              Australian Consumer Law. If the service fails to meet a consumer guarantee, you are
              entitled to a remedy under that law, which may include a refund. We will also consider
              refunds at our discretion for billing errors or technical failures that prevented
              delivery. Contact{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-3">
              <li>Use Docs Rok for any unlawful purpose or in violation of any applicable law</li>
              <li>Generate documents for businesses you are not authorised to represent</li>
              <li>Resell, redistribute, or sublicense the documents you generate as your own product</li>
              <li>Attempt to reverse-engineer or copy the document generation system</li>
              <li>Provide false information about your business during onboarding</li>
              <li>Use automated tools to scrape, extract, or abuse the service</li>
              <li>Attempt to gain unauthorised access to other users&rsquo; accounts or data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Intellectual property</h2>
            <p>
              The Docs Rok platform, including its software, design, and underlying document generation
              system, is owned by us and protected by copyright and other intellectual property laws.
            </p>
            <p className="mt-3">
              Documents generated for your business are yours to use for your own business purposes.
              You may edit, print, distribute to your staff and subcontractors, and retain them. You
              may not resell or sublicense them as templates to others.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by Australian law, Docs Rok and its operators are not
              liable for:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-3">
              <li>Any business, financial, contractual, or commercial loss arising from your use of documents generated by Docs Rok</li>
              <li>Disputes with customers, staff, or subcontractors arising from terms, policies, or quotes generated by Docs Rok</li>
              <li>Any loss or damage arising from your reliance on documents generated by Docs Rok without independent review</li>
              <li>Service interruptions, data loss, or technical errors</li>
              <li>Indirect, incidental, consequential, or special damages of any kind</li>
            </ul>
            <p className="mt-3">
              Our total liability to you for any claim arising from use of Docs Rok is limited to the
              amount you paid us in the three months preceding the claim.
            </p>
            <p className="mt-3">
              Nothing in these Terms excludes liability that cannot be excluded under Australian consumer
              law, including guarantees under the <em>Competition and Consumer Act 2010</em> (Cth).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">11. Service availability</h2>
            <p>
              We aim to provide a reliable service but do not guarantee uninterrupted availability.
              We may carry out maintenance, updates, or experience outages. We will endeavour to
              notify users of planned maintenance in advance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">12. Termination</h2>
            <p>
              We may suspend or terminate your account if you breach these Terms, engage in abusive
              or fraudulent activity, or if required to do so by law. We will provide notice where
              reasonably practicable. Upon termination, your access to documents will cease. You may
              request a copy of your data within 30 days of termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">13. Changes to terms</h2>
            <p>
              We may update these Terms from time to time. Material changes will be notified by email
              at least 14 days before taking effect. Continued use of Docs Rok after the effective
              date constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">14. Governing law</h2>
            <p>
              These Terms are governed by the laws of Queensland, Australia. Any disputes will be
              subject to the exclusive jurisdiction of the courts of Queensland.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">15. Contact</h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-gray-100 py-8 px-4 text-center text-xs text-gray-400">
        <Link href="/" className="text-orange-600 font-semibold">Docs Rok</Link>
        {' · '}
        <Link href="/privacy" className="hover:text-gray-600">Privacy Policy</Link>
        {' · '}
        <Link href="/terms" className="hover:text-gray-600">Terms of Service</Link>
      </footer>
    </div>
  )
}
