import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Docs Rok',
  description: 'Terms of Service for Docs Rok — the WHS compliance document platform for Australian construction businesses.',
}

const LAST_UPDATED = '28 June 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-orange-600 font-bold text-lg tracking-tight">Docs Rok</Link>
          <Link href="/login" className="text-sm text-gray-500 hover:text-gray-800 transition-colors">Sign in</Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: {LAST_UPDATED}</p>

        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-10">
          <p className="text-sm text-amber-800 font-medium">
            Important: Documents generated by Docs Rok are templates to assist with WHS compliance.
            They do not constitute legal advice and do not guarantee compliance with applicable
            legislation. You remain responsible for implementing safe work practices on your sites.
          </p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-gray-700">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Agreement to terms</h2>
            <p>
              By creating an account with Docs Rok (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you (&ldquo;you&rdquo;, &ldquo;the subscriber&rdquo;)
              agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not
              use the service.
            </p>
            <p className="mt-3">
              These Terms form a legally binding agreement between you and Docs Rok, governed by the
              laws of Queensland, Australia.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Description of service</h2>
            <p>
              Docs Rok is a software-as-a-service platform that generates Work Health and Safety (WHS)
              compliance document templates for Australian construction businesses operating in
              Queensland and New South Wales. Documents are generated using artificial intelligence
              based on information you provide about your business.
            </p>
            <p className="mt-3">Documents generated by Docs Rok include:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>WHS Policy</li>
              <li>Safe Work Method Statements (SWMS) for high-risk construction activities</li>
              <li>Hazard Register</li>
              <li>Incident Report Form</li>
              <li>Emergency Procedures</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Important disclaimer — not legal advice</h2>
            <div className="bg-gray-50 rounded-lg p-4 space-y-3">
              <p>
                <strong>Documents generated by Docs Rok are templates only.</strong> They are not legal advice
                and do not constitute a guarantee of compliance with the{' '}
                <em>Work Health and Safety Act 2011</em> (Qld),{' '}
                <em>Work Health and Safety Act 2011</em> (NSW), or any other legislation.
              </p>
              <p>
                WHS compliance depends on how you implement safe work practices on your specific sites,
                with your specific workers, plant, and equipment. A document alone does not make a
                workplace safe or legally compliant.
              </p>
              <p>
                You must review each document for accuracy before using it. Site-specific details
                (assembly points, site addresses, nearest hospital, first aid officer details)
                must be completed by you before distribution to workers.
              </p>
              <p>
                For complex projects, site-specific risk assessments, or incident investigations,
                you should engage a qualified WHS professional. Docs Rok is not a substitute for
                professional WHS advice.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Your account</h2>
            <p>
              You must provide accurate information when creating your account. You are responsible
              for maintaining the security of your password and for all activity under your account.
              Notify us immediately at{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>{' '}
              if you suspect unauthorised access.
            </p>
            <p className="mt-3">
              Each account may only be used by one business entity. You may not share your account
              credentials with other businesses or use the service to generate documents for businesses
              other than your own (except where you are an authorised representative of that business).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Free trial</h2>
            <p>
              New accounts receive a 14-day free trial. No credit card is required to start a trial.
              At the end of the trial period, your account will be restricted until you subscribe to
              a paid plan. Documents you generated during the trial remain accessible once you subscribe.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Subscription and billing</h2>
            <p>
              Paid subscriptions are billed monthly in advance in Australian Dollars (AUD).
              GST (10%) is added where applicable under Australian tax law.
            </p>
            <p className="mt-3">Current subscription plans:</p>
            <div className="overflow-x-auto mt-3">
              <table className="w-full border border-gray-200 rounded-lg overflow-hidden text-xs">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="text-left p-3 font-semibold text-gray-700">Plan</th>
                    <th className="text-left p-3 font-semibold text-gray-700">Price (ex-GST)</th>
                    <th className="text-left p-3 font-semibold text-gray-700">Features</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  <tr>
                    <td className="p-3 font-medium">Core</td>
                    <td className="p-3">$89 AUD/month</td>
                    <td className="p-3">All 5 document types, SWMS for selected activities</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium">Plus</td>
                    <td className="p-3">$149 AUD/month</td>
                    <td className="p-3">Core + all 10 SWMS activities, priority updates</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium">Team</td>
                    <td className="p-3">$249 AUD/month</td>
                    <td className="p-3">Plus + up to 5 team members, multiple profiles</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mt-3">
              Payments are processed by Stripe, Inc. By subscribing, you authorise Stripe to charge
              your payment method on a recurring monthly basis until you cancel.
            </p>
            <p className="mt-3">
              We reserve the right to change pricing with 30 days&rsquo; notice by email. Price changes
              take effect at your next renewal date after the notice period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Cancellation and refunds</h2>
            <p>
              You may cancel your subscription at any time from your account dashboard (Manage billing).
              Cancellation takes effect at the end of your current billing period — you retain access
              until then.
            </p>
            <p className="mt-3">
              We do not offer refunds for partial months. If you cancel mid-cycle, you retain access
              until the period ends and will not be charged again.
            </p>
            <p className="mt-3">
              Exceptions may be considered at our discretion for billing errors or technical failures
              that prevented access to the service. Contact{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-3">
              <li>Use Docs Rok for any unlawful purpose or in violation of any applicable law</li>
              <li>Generate documents for businesses you are not authorised to represent</li>
              <li>Resell, redistribute, or sublicense the documents you generate as your own product</li>
              <li>Attempt to reverse-engineer or copy the document generation system</li>
              <li>Provide false information about your business during onboarding</li>
              <li>Use automated tools to scrape, extract, or abuse the service</li>
              <li>Attempt to gain unauthorised access to other users&rsquo; accounts or data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Intellectual property</h2>
            <p>
              The Docs Rok platform, including its software, design, and underlying document generation
              system, is owned by us and protected by copyright and other intellectual property laws.
            </p>
            <p className="mt-3">
              Documents generated for your business are yours to use for your own WHS compliance
              purposes. You may edit, print, distribute to your workers, and retain them. You may not
              resell or sublicense them as templates to others.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by Australian law, Docs Rok and its operators are not
              liable for:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-3">
              <li>Any workplace incident, injury, illness, or death, whether or not documents generated by Docs Rok were in use at the time</li>
              <li>Regulatory penalties, fines, or enforcement action by WHSQ, SafeWork NSW, or any other regulator</li>
              <li>Any loss or damage arising from your reliance on documents generated by Docs Rok without independent review</li>
              <li>Service interruptions, data loss, or technical errors</li>
              <li>Indirect, incidental, consequential, or special damages of any kind</li>
            </ul>
            <p className="mt-3">
              Our total liability to you for any claim arising from use of Docs Rok is limited to the
              amount you paid us in the three months preceding the claim.
            </p>
            <p className="mt-3">
              Nothing in these Terms excludes liability that cannot be excluded under Australian consumer
              law, including guarantees under the <em>Competition and Consumer Act 2010</em> (Cth).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">11. Service availability</h2>
            <p>
              We aim to provide a reliable service but do not guarantee uninterrupted availability.
              We may carry out maintenance, updates, or experience outages. We will endeavour to
              notify users of planned maintenance in advance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">12. Termination</h2>
            <p>
              We may suspend or terminate your account if you breach these Terms, engage in abusive
              or fraudulent activity, or if required to do so by law. We will provide notice where
              reasonably practicable. Upon termination, your access to documents will cease. You may
              request a copy of your data within 30 days of termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">13. Changes to terms</h2>
            <p>
              We may update these Terms from time to time. Material changes will be notified by email
              at least 14 days before taking effect. Continued use of Docs Rok after the effective
              date constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">14. Governing law</h2>
            <p>
              These Terms are governed by the laws of Queensland, Australia. Any disputes will be
              subject to the exclusive jurisdiction of the courts of Queensland.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">15. Contact</h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="mailto:support@docsrok.com.au" className="text-orange-600 hover:underline">support@docsrok.com.au</a>.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-gray-100 py-8 px-4 text-center text-xs text-gray-400">
        <Link href="/" className="text-orange-600 font-semibold">Docs Rok</Link>
        {' · '}
        <Link href="/privacy" className="hover:text-gray-600">Privacy Policy</Link>
        {' · '}
        <Link href="/terms" className="hover:text-gray-600">Terms of Service</Link>
      </footer>
    </div>
  )
}
